secrets:
  jwt: "kfmmkmkmkmk"
  salt: "lkfnmejkm2"
app:
  port: "9000"
postgres:
  host: "auth-db"
  port: 5432
  user: "root"
  password: "root"
  dbname: "auth-db"
  sslmode: "disable"

env: local

token_ttl: 1h
