version: "3.8"

services:
  auth-service-migrations:
    image: migrate/migrate:latest
    command:
      [
        "-path",
        "/database",
        "-database",
        "postgres://root:root@auth-db:5432/auth-db?sslmode=disable",
        "up",
      ]

    volumes:
      - ../../build/auth-service-migrations/migrations:/database

    depends_on:
      - auth-db
#     networks:
#       - auth-go-net

# networks:
#   auth-go-net:
#     name: auth-go-net
#     external: true
