version: "3.8"

services:
  auth-service:
    container_name: auth-service
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        TARGET_ARCH: ${TARGET_ARCH}
        TARGET_SERVICE: auth-service
    volumes:
      - ../env/local/config-local.yaml:/go/config/config.yaml
    depends_on:
      - auth-db
    # networks:
    #   - auth-go-net
    ports:
      - "9000:9000"
  pgadmin:
    image: dpage/pgadmin4:6.14
    ports:
      - "5050:80"
    # networks:
    #   - auth-go-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
