version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - auth-go:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    networks:
      - auth-go-net
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost",
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

volumes:
  auth-go:

networks:
  auth-go-net:
    name: auth-go-net
    external: true
